# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('located_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_api.City')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fb_id', models.IntegerField(unique=True)),
                ('facebook_id', models.CharField(max_length=50)),
                ('cr_number', models.CharField(default='default', max_length=10)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('mobile_number', models.IntegerField(default=None, unique=True)),
                ('whatsapp_number', models.IntegerField(default=None, unique=True)),
                ('postal_address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('year_of_study', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth')], max_length=7)),
                ('whatsapp_share', models.IntegerField(default=0)),
                ('fort_ideas', models.IntegerField(default=0)),
                ('total_ideas', models.IntegerField(default=0)),
                ('fort_fb_likes', models.IntegerField(default=0)),
                ('total_fb_likes', models.IntegerField(default=0)),
                ('fort_fb_share', models.IntegerField(default=0)),
                ('total_fb_share', models.IntegerField(default=0)),
                ('twitter_share', models.IntegerField(default=0)),
                ('fort_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('present_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_api.City')),
                ('present_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_api.College')),
            ],
        ),
    ]
