# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cr_number',
            new_name='mi_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fb_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fort_fb_likes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fort_fb_share',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fort_ideas',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fort_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_fb_likes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_fb_share',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_ideas',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_share',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='whatsapp_share',
        ),
    ]
