# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_api', '0005_auto_20170616_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mi_number',
            field=models.CharField(default='default', max_length=10, unique=True),
        ),
    ]
