# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant_api', '0006_auto_20170627_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('name',)},
        ),
    ]
