# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_api', '0008_auto_20170726_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fb_id',
            field=models.IntegerField(default=0),
        ),
    ]
