# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workshop',
        ),
        migrations.RenameField(
            model_name='workshopsgenre',
            old_name='genre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='workshopsevent',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='workshops.WorkshopsGenre'),
        ),
    ]
