# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronites', '0002_auto_20170729_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pronite',
        ),
        migrations.RenameField(
            model_name='pronitesgenre',
            old_name='genre',
            new_name='name',
        ),
    ]
