# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informals', '0002_informalsgenre_infromalsevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informals',
            new_name='Informal',
        ),
    ]
