# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informals', '0004_auto_20170626_0959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfromalsEvent',
            new_name='InformalsEvent',
        ),
    ]
