# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informals', '0005_auto_20170627_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Informal',
        ),
        migrations.AlterField(
            model_name='informalsevent',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='informals.InformalsGenre'),
        ),
    ]
