# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proshows', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proshow',
        ),
        migrations.RenameField(
            model_name='proshowsgenre',
            old_name='genre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='proshowsevent',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proshows.ProshowsGenre'),
        ),
    ]
