# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='IITB', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='participants',
            field=models.ManyToManyField(blank=True, to='competitions.Group'),
        ),
    ]
