# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_individualevent_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualevent',
            name='team_id',
        ),
        migrations.AddField(
            model_name='group',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competitions.IndividualEvent'),
        ),
    ]
