# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_group_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualevent',
            name='groups_part',
            field=models.ManyToManyField(blank=True, to='competitions.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.IndividualEvent'),
        ),
    ]
